
<p>&nbsp;</p>
<p><strong>Gegenstand</strong></p>
<p>Der Diensteanbieter freut sich über das Interesse an seiner Website. Der Schutz der personenbezogenen Daten (nachfolgend „Daten“) des Nutzers ist ihm ein wichtiges Anliegen. Nachfolgend möchte er den Nutzer daher darüber informieren, ob und ggf. welche Daten er erhebt, wie er diese Daten verwendet und welche Schutzmaßnahmen er in technischer und organisatorischer Hinsicht getroffen hat.</p>
<p>&nbsp;</p>
<p><strong>Verantwortliche Stelle/Diensteanbieter</strong></p>
<p>Verantwortliche Stelle im Sinne des Bundesdatenschutzgesetzes und zugleich Diensteanbieter im Sinne des Telemediengesetzes ist die NETVAI UG (haftungsbeschränkt). Nähere Angaben sind im Impressum dieser Website zu finden.</p>
<p>&nbsp;</p>
<p><strong>Erhebung und Verwendung von Daten</strong></p>
<p>Art, Umfang und Zweck der Erhebung und Verwendung der Daten des Nutzers unterscheiden sich danach, ob der Nutzer die Website nur zum Abruf von Informationen besucht oder ob er zusätzliche Leistungen in Anspruch nimmt.</p>
<p>Nur informatorische Nutzung</p>
<p>Für die nur informatorische Nutzung der Website ist es grundsätzlich nicht erforderlich, dass der Nutzer Daten angibt. Vielmehr erhebt und verwendet der Diensteanbieter in diesem Fall nur diejenigen Daten, die ihm der Webbrowser des Nutzers automatisch übermittelt bzw. die der Webserver erfasst. Dies sind:</p>
<p>• Datum und Uhrzeit des Abrufs der Website durch den Nutzer,<br />
• seinen Webbrowsertyp,<br />
• seine Webbrowser-Einstellungen,<br />
• das von ihm verwendete Betriebssystem,<br />
• die von ihm zuletzt besuchte Website,<br />
• die übertragene Datenmenge und der Zugriffsstatus,<br />
• seine IP-Adresse.</p>
<p>Diese Daten erhebt und verwendet der Diensteanbieter bei einem nur informatorischen Besuch ausschließlich in nicht-personenbezogener Form. Dies erfolgt, um die Nutzung der Website überhaupt zu ermöglichen, zu statistischen Zwecken, zur Verbesserung der Website und zu sicherheitstechnischen Zwecken. Die IP-Adresse des Nutzers speichert der Diensteanbieter nur für die Dauer des Besuchs des Nutzers, eine personenbezogene Auswertung findet nicht statt.</p>
<p>Nutzung von Angeboten</p>
<p>Falls der Nutzer zusätzliche Leistungen in Anspruch nehmen will, ist es dagegen notwendig, dass er weitere Daten angibt. Es handelt sich um diejenigen Daten des Nutzers, die zur Abwicklung der gewünschten Leistungen erforderlich sind, zum Beispiel seinen Name und seine Anschrift, falls er sich für die Nutzung der Website registriert. Weitere Angaben kann er freiwillig tätigen; sie sind entsprechend markiert.</p>
<p>Der Diensteanbieter erhebt und verwendet die Daten des Nutzers nur, um die gewünschten Leistungen zu erbringen. Die Daten des Nutzers werden hierzu ggf. an den Diensteanbieter unterstützende Dienstleister weitergegeben, die er selbstverständlich sorgfältig ausgewählt hat. Dabei kann es sich vor allem um technische Dienstleister handeln. Die Weitergabe der Daten des Nutzers an andere Dritte erfolgt ansonsten nur, soweit der Diensteanbieter dazu gesetzlich verpflichtet ist.</p>
<p>&nbsp;</p>
<p><strong>Newsletter</strong></p>
<p>Mit seiner ausdrücklichen Einwilligung möchte der Diensteanbieter dem Nutzer gern gelegentlich seinen Newsletter mit interessanten Informationen zu sich und seinem Leistungsangebot zukommen lassen. Um sich beim Newsletter anmelden zu können, benötigt der Diensteanbieter neben der Einwilligung des Nutzers mindestens seine E-Mail-Adresse, an die der Newsletter versendet werden soll. Etwaige weitere Angaben sind freiwillig.</p>
<p>Für den Newsletterversand verwendet der Diensteanbieter das sog. Double-Opt-In-Verfahren, d.h. der Diensteanbieter wird dem Nutzer erst dann den Newsletter zusenden, wenn der Nutzer zuvor seine Anmeldung über eine ihm zu diesem Zweck zugesandte Bestätigungs-E-Mail per darin enthaltenem Link bestätigt. Damit möchte der Diensteanbieter sicherstellen, dass nur der Nutzer selbst sich als Inhaber der angegebenen E-Mail-Adresse zum Newsletter anmelden kann.</p>
<p>Der Nutzer kann den Newsletter jederzeit abbestellen. Dazu kann er dem Diensteanbieter entweder eine formlose E-Mail zusenden oder über den Link am Ende des Newsletters eine Stornierung vornehmen. Die E-Mail-Adresse des Diensteanbieters ist im Impressum dieser Website zu finden.</p>
<p>&nbsp;</p>
<p><strong>Einsatz von Cookies</strong></p>
<p>Der Diensteanbieter setzt auf der Website sog. Cookies ein. Cookies sind kleine Textdateien, die im Rahmen des Besuchs der Website vom Webserver an den Webbrowser des Nutzers gesandt und von diesem auf dem Rechner des Nutzers für einen späteren Abruf vorgehalten werden. Zweck dieser Cookies ist es, den Rechner des Nutzers während der Nutzung der Website zu identifizieren.</p>
<p>Ob Cookies gesetzt und abgerufen werden können, kann der Nutzer durch die Einstellungen in seinem Webbrowser selbst bestimmen. Er kann in seinem Webbrowser etwa das Speichern von Cookies gänzlich deaktivieren, es auf bestimmte Websites beschränken oder seinen Webbrowser so konfigurieren, dass er den Nutzer automatisch benachrichtigt, sobald ein Cookie gesetzt werden soll und den Nutzer um Rückmeldung dazu bittet. Für den vollen Funktionsumfang der Website ist es allerdings aus technischen Gründen erforderlich, Cookies zuzulassen.</p>
<p>Eine Erhebung oder Speicherung personenbezogener Daten in Cookies findet in diesem Zusammenhang nicht statt. Der Diensteanbieter setzt auch keine Techniken ein, die die durch Cookies anfallenden Informationen mit Nutzerdaten verbinden.</p>
<p>&nbsp;</p>
<p><strong>Einsatz von Google Analytics</strong></p>
<p>Dem Diensteanbieter ist es wichtig, die Website möglichst optimal auszugestalten und damit für Besucher attraktiv zu machen. Dazu ist es nötig, dass er weiß, welche Teile davon wie bei seinen Besuchern ankommen. Hierfür setzt der Diensteanbieter Google Analytics ein, einen Webanalysedienst der Google Inc. (nachfolgend „Google”). Google Analytics verwendet ebenfalls Cookies. Die Cookies ermöglichen eine Analyse der Benutzung der Website durch den Nutzer.</p>
<p>Die mithilfe der Cookies erzeugten Informationen werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Die IP-Adresse des Nutzers wird von Google jedoch zuvor innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und erst dort gekürzt.</p>
<p>In Auftrag des Diensteanbieters wird Google diese Informationen benutzen, um die Nutzung der Website durch den Nutzer auszuwerten, um Reports über die Websiteaktivitäten zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen gegenüber dem Diensteanbieter als Websitebetreiber zu erbringen. Die im Rahmen von Google Analytics vom Browser des Nutzers übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt.</p>
<p>Der Nutzer kann die Speicherung der Cookies durch eine entsprechende Einstellung seines Webbrowsers verhindern; der Diensteanbieter weist jedoch darauf hin, dass der Nutzer in diesem Fall ggf. nicht sämtliche Funktionen dieser Website vollumfänglich wird nutzen können. Der Nutzer kann darüber hinaus die Erfassung der durch den Cookie erzeugten und auf seine Nutzung der Website bezogenen Daten (inkl. seiner IP-Adresse) an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem er das unter dem folgenden Link verfügbare Webbrowser-Plug-in herunterlädt und installiert: https://tools.google.com/dlpage/gaoptout?hl=de. Alternativ, insbesondere bei Nutzung ein mobilen Geräts, das die Installation von Webbrowser-Plug-ins nicht unterstützt, kann der Nutzer mithilfe des folgenden Links einen Opt-Out-Cookie setzen: javascript:gaOptout().</p>
<p>&nbsp;</p>
<p><strong>Widerrufs- und Widerspruchsrecht</strong></p>
<p>Der Diensteanbieter weist darauf hin, dass der Nutzer eine dem Diensteanbieter erteilte datenschutzrechtliche Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen kann. Einer etwaigen im Rahmen dieser Datenschutzerklärung erfolgenden Erstellung von Nutzungsprofilen zu Werbe- und Marktforschungszwecken sowie zur bedarfsgerechten Ausgestaltung der Website kann der Nutzer ebenfalls jederzeit widersprechen. Dazu wendet er sich am besten formlos per E-Mail an den Diensteanbieter. Die E-Mail-Adresse findet der Nutzer im Impressum dieser Website.</p>
<p>&nbsp;</p>
<p><strong>Datensicherheit</strong></p>
<p>Der Diensteanbieter setzt zudem technische und organisatorische Sicherheitsmaßnahmen ein, um die Daten des Nutzers zu schützen, insbesondere gegen zufällige oder vorsätzliche Manipulation, Verlust, Zerstörung oder gegen den Angriff unberechtigter Personen. Die Sicherheitsmaßnahmen werden entsprechend der technologischen Entwicklung fortlaufend verbessert. Der Bestellvorgang, insbesondere die Eingabe von Zahlungs- und Kreditkartendaten, wird per SSL-Technik verschlüsselt, um Zugriffe unberechtigter Dritter zu verhindern.</p>